# -*- coding: utf-8 -*-
"""Untitled17.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_jukKViFPjKsvrAmXKMLjLyfclygoa5P
"""

# Install dependencies


import phonenumbers
from phonenumbers import geocoder
import requests

def get_sim_location(phone_number):
    """
    Find SIM location using phone number.

    Args:
        phone_number (str): Phone number in international format (e.g., +1234567890)

    Returns:
        dict: Location information or error message
    """
    try:
        # Parse the phone number
        parsed_num = phonenumbers.parse(phone_number)

        # Get basic location info
        location = geocoder.description_for_number(parsed_num, 'en')

        # Use OpenCage for more detailed geocoding
        api_key = "6d0e711d72d74daeb2b0bfd2a5cdfdba"
        query = f"{parsed_num.country_code} {parsed_num.national_number}"
        response = requests.get(
            f"https://api.opencagedata.com/geocode/v1/json?q={query}&key={api_key}"
        )

        if response.status_code == 200:
            data = response.json()
            if data['results']:
                coords = data['results'][0]['geometry']
                return {
                    'country': location,
                    'coordinates': coords,
                    'formatted_address': data['results'][0]['formatted']
                }
            else:
                return {'error': 'Location not found'}
        else:
            return {'error': f'API request failed: {response.text}'}

    except Exception as e:
        return {'error': str(e)}

# Example usage
phone_number = "+917009546709"  # Replace with actual number
location_info = get_sim_location(phone_number)
print(location_info)
